### PR TITLE
Fix frame sizes, Read correct text encoding, NNBD

### PR DESCRIPTION
**Pull request by moffatman**
The frame size wasn't being calculated correctly. For images this meant it was not getting all the image data, resulting in corrupted images. 

The text encoding wasn't being read properly, resulting in foreign characters being lost. 

Include @4-alok's null-safety work.

### CODE REVIEW

**Review by sanket143 — APPROVED** [review]

**Comment by moffatman** [comment]
@sanket143 Going to merge it?

**Comment by sanket143** [comment]
thanks, @moffatman and @4-alok for contributing

**Comment by StarBattle08** [comment]
I came from #1 and still have the issue where it only outputs the "Version". I'm trying to display the image from the mp3 but the data isn't there.

**Comment by sanket143** [comment]
@StarBattle08  will it be possible for you to share that mp3 file?

**Comment by StarBattle08** [comment]
https://kajian.net/MP3/Ceramah/Abu%20Abdil%20Muhsin%20Firanda%20Andirja/Tafsir%20Juz%2012%20Surat%20Yusuf/08.%20Tafsir%20Surat%20Yusuf%208%20Ayat%2067-80.mp3

**Comment by StarBattle08** [comment]
First of all, thanks for updating the package. #14 It properly outputs the tags now. But i can't seem to display the image cover due to invalid base64 🤷. Is it because it has to do with it being encoded by itunes? I tried some other mp3 files and it works fine.

the tags output:
```
{Version: v2.2.0, COMM: {eng: {iTunPGAP: 0, iTunNORM:  000002E1 000002F2 00002C8D 00002B28 001A5500 001A5500 00008D71 00008D1F 003038E8 003038E8, iTunSMPB:  00000000 00000210 00000956 000000000927DB9A 00000000 0124F860 00000000 00000000 00000000 00000000 00000000 00000000}}, EncodedBy: iTunes 12.8.2.3, APIC: {mime: JPG\^C, textEncoding: 0, picType: , description: ÿØÿà, base64: EEpGSUYAAQEBAEgASAAA/9sAQwAIBgYHBgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMcHCg3KSwwMTQ0NB8nOT04MjwuMzQy/9sAQwEJCQkMCwwYDQ0YMiEcITIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy/8AAEQgC0AUAAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKB<…>
```

**Pull request merged**
